version: '3'
services:
  tomcat:
    image: tomcat:8.5.35
    container_name: tomcat
    volumes:
      - ../../../target/servlet-calculator-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
      - ../../../target/servlet-calculator-1.0-SNAPSHOT:/usr/local/tomcat/webapps/ROOT
    ports:
      - "8080:8080"